write-host -f green "read this from the pipe: $input"
""
write "write"
echo "echo"
"just quotes"
write-output "write-output"
write-host "write-host"
#write-error "write-error"
write-warning "write-warning"
""
""
"now all the about with input. tell me a secret:"
$dataRead = read-host 
""
""
write "write $dataRead"
echo "echo $dataRead"
"just quotes $dataRead"
write-output "write-output $dataRead"
write-host "write-host $dataRead"
#write-error "write-error $dataRead"
write-warning "write-warning $dataRead"


